# build_land.py - Natural Earth 50m 해안선(단순화 없음) -> land_data.js
# 실행: python build_land.py     (shapely 불필요, 순수 표준 라이브러리)
import json, base64, os, struct, urllib.request

SRC = ("https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
       "master/geojson/ne_50m_land.geojson")
HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "ne_50m_land.geojson")
OUT = os.path.join(HERE, "land_data.js")
NDEC = 2            # 0.01도 = 약 1.11km (int16 저장 한계와 일치)
MIN_AREA = 0.001    # deg^2, 이보다 작은 폴리곤은 제외 (노이즈 제거)

def fetch():
    if os.path.exists(CACHE) and os.path.getsize(CACHE) > 500000:
        print("cache hit:", CACHE); return
    print("downloading Natural Earth 50m land (~1.6MB) ...")
    urllib.request.urlretrieve(SRC, CACHE)
    print("saved:", CACHE, os.path.getsize(CACHE), "bytes")

def ring_area(pts):
    a = 0.0
    n = len(pts)
    for i in range(n):
        x1, y1 = pts[i]; x2, y2 = pts[(i+1) % n]
        a += x1*y2 - x2*y1
    return abs(a)/2.0

def collect(geom, out):
    t = geom["type"]; c = geom["coordinates"]
    polys = [c] if t == "Polygon" else c
    for poly in polys:
        if not poly: continue
        if ring_area(poly[0]) < MIN_AREA:   # 외곽링 면적으로 판정
            continue
        for ring in poly:
            pts = []; last = None
            for xy in ring:
                q = (round(xy[0], NDEC), round(xy[1], NDEC))
                if q != last:
                    pts.append(q); last = q
            if len(pts) >= 4:
                out.append(pts)

def main():
    fetch()
    d = json.load(open(CACHE, encoding="utf-8"))
    rings = []
    for f in d["features"]:
        collect(f["geometry"], rings)
    npts = sum(len(r) for r in rings)
    # 이진 인코딩: [uint32 ringCount][uint32 len]*N [int16 lon*100, int16 lat*100]*P
    buf = bytearray()
    buf += struct.pack("<I", len(rings))
    for r in rings:
        buf += struct.pack("<I", len(r))
    mx = 0
    for r in rings:
        for (x, y) in r:
            xi = int(round(x*100)); yi = int(round(y*100))
            xi = max(-32768, min(32767, xi)); yi = max(-32768, min(32767, yi))
            mx = max(mx, abs(xi), abs(yi))
            buf += struct.pack("<hh", xi, yi)
    assert mx <= 32767, "int16 overflow"
    payload = base64.b64encode(bytes(buf)).decode()
    js = ("// AUTO-GENERATED by build_land.py - DO NOT EDIT BY HAND\n"
          "// Source: Natural Earth 1:50m land (public domain) - naturalearthdata.com\n"
          "// via nvkelso/natural-earth-vector. See SOURCES_LICENSE.md\n"
          "// Format: int16 lon*100, lat*100 (0.01deg ~ 1.11km). No simplification.\n"
          "window.LANDBIN = { rings: %d, points: %d, scale: 100, data: \"%s\" };\n"
          % (len(rings), npts, payload))
    open(OUT, "w", encoding="utf-8").write(js)
    print("rings: %d | points: %d" % (len(rings), npts))
    print("binary %d KB -> %s (%d KB)"
          % (len(buf)//1024, OUT, os.path.getsize(OUT)//1024))

if __name__ == "__main__":
    main()
