# build_currents.py - NASA OSCAR 표면해류 -> 2도 격자 u/v -> currents_data.js
# 실행: python build_currents.py
import json, base64, os, urllib.request

SRC = ("https://raw.githubusercontent.com/cambecc/earth/master/"
       "public/data/oscar/20140131-surface-currents-oscar-0.33.json")
HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "oscar_raw.json")
OUT = os.path.join(HERE, "currents_data.js")
NX, NY = 180, 90          # 2도 격자
QSTEP = 2.0               # 양자화 단위: 2 cm/s -> int8

def fetch():
    if os.path.exists(CACHE) and os.path.getsize(CACHE) > 1000000:
        print("cache hit:", CACHE); return
    print("downloading OSCAR (~5MB) ...")
    urllib.request.urlretrieve(SRC, CACHE)
    print("saved:", CACHE, os.path.getsize(CACHE), "bytes")

def downsample(rec_u, rec_v):
    h = rec_u["header"]
    nx, ny = h["nx"], h["ny"]
    lo1, la1 = h["lo1"], h["la1"]
    dx, dy = h["dx"], h["dy"]
    su = [0.0]*(NX*NY); sv = [0.0]*(NX*NY); cnt = [0]*(NX*NY)
    U = rec_u["data"]; V = rec_v["data"]
    for r in range(ny):
        lat = la1 - r*dy
        tj = int((90.0 - lat)//2)
        tj = 0 if tj < 0 else (NY-1 if tj >= NY else tj)
        base = r*nx; row = tj*NX
        for c in range(nx):
            u = U[base+c]
            if u is None: continue
            v = V[base+c]
            if v is None: continue
            lon = lo1 + c*dx
            lonw = ((lon + 180.0) % 360.0) - 180.0
            ti = int((lonw + 180.0)//2)
            ti = 0 if ti < 0 else (NX-1 if ti >= NX else ti)
            k = row + ti
            su[k] += u; sv[k] += v; cnt[k] += 1
    gu = [ (su[i]/cnt[i]) if cnt[i] else 0.0 for i in range(NX*NY) ]
    gv = [ (sv[i]/cnt[i]) if cnt[i] else 0.0 for i in range(NX*NY) ]
    return gu, gv, cnt

def quant(vals):
    b = bytearray()
    for x in vals:
        q = int(round(x*100.0/QSTEP))       # m/s -> cm/s -> /2
        q = -127 if q < -127 else (127 if q > 127 else q)
        b.append(q & 0xFF)
    return b

def main():
    fetch()
    d = json.load(open(CACHE, encoding="utf-8"))
    ru = next(r for r in d if r["header"]["parameterNumberName"].startswith("U_"))
    rv = next(r for r in d if r["header"]["parameterNumberName"].startswith("V_"))
    gu, gv, cnt = downsample(ru, rv)
    ocean = sum(1 for c in cnt if c)
    sp = [ (gu[i]**2+gv[i]**2)**0.5 for i in range(NX*NY) if cnt[i] ]
    sp.sort()
    ref = sp[int(len(sp)*0.99)]             # p99 유속 = 정규화 기준
    payload = base64.b64encode(bytes(quant(gu)+quant(gv))).decode()
    js = (
      "// AUTO-GENERATED by build_currents.py - DO NOT EDIT BY HAND\n"
      "// Source: NASA OSCAR surface currents 2014-01-31 (JPL PODAAC, public domain)\n"
      "// JSON redistribution: cambecc/earth (MIT). See SOURCES_LICENSE.md\n"
      "window.CURRENTS = {\n"
      "  nx: %d, ny: %d,\n"
      "  quantStep: %.1f,   // int8 1단위 = %.1f cm/s\n"
      "  refMs: %.4f,       // p99 유속(m/s) = 정규화 기준\n"
      "  data: \"%s\"\n"
      "};\n" % (NX, NY, QSTEP, QSTEP, ref, payload)
    )
    open(OUT, "w", encoding="utf-8").write(js)
    print("ocean cells: %d / %d" % (ocean, NX*NY))
    print("max %.2f m/s | p99(ref) %.3f m/s" % (max(sp), ref))
    print("wrote %s (%d KB)" % (OUT, os.path.getsize(OUT)//1024))

if __name__ == "__main__":
    main()
