# build_depth.py - Natural Earth 10m 등심선 -> bathy_data.js
# 실행: python build_depth.py     (외부 패키지 불필요)
import json, base64, os, struct, urllib.request

BASE = ("https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
        "master/geojson/")
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "bathy_data.js")
NDEC = 2          # 0.01도 = 1.11km (land_data.js 와 동일)
TOL = 0.03        # 단순화 허용오차(도) = 3.34km

# (파일, 수심m, 최소폴리곤면적deg², 최소구멍면적deg²)
BANDS = [
    ("ne_10m_bathymetry_K_200",   200, 0.5,  0.3),
    ("ne_10m_bathymetry_J_1000", 1000, 0.5,  0.3),
    ("ne_10m_bathymetry_G_4000", 4000, 0.8,  0.5),
    ("ne_10m_bathymetry_E_6000", 6000, 0.05, 0.05),   # 해구는 폭이 좁아 작게
]

def fetch(name):
    p = os.path.join(HERE, name + ".geojson")
    if os.path.exists(p) and os.path.getsize(p) > 100000:
        return p
    print("  downloading", name, "...")
    urllib.request.urlretrieve(BASE + name + ".geojson", p)
    return p

def shoelace(pts):
    a = 0.0
    n = len(pts)
    for i in range(n):
        x1, y1 = pts[i]; x2, y2 = pts[(i+1) % n]
        a += x1*y2 - x2*y1
    return abs(a)/2.0

def simplify(pts, tol):
    """Douglas-Peucker (반복형 - 재귀 깊이 제한 회피). 닫힌 링 가정."""
    n = len(pts)
    if n < 4:
        return pts
    keep = [False]*n
    keep[0] = keep[n-1] = True
    stack = [(0, n-1)]
    t2 = tol*tol
    while stack:
        i, j = stack.pop()
        if j <= i+1:
            continue
        ax, ay = pts[i]; bx, by = pts[j]
        dx, dy = bx-ax, by-ay
        dd = dx*dx + dy*dy
        best = -1.0; bi = -1
        for k in range(i+1, j):
            px, py = pts[k]
            if dd == 0:
                ex, ey = px-ax, py-ay
                d2 = ex*ex + ey*ey
            else:
                t = ((px-ax)*dx + (py-ay)*dy)/dd
                if t < 0: t = 0.0
                elif t > 1: t = 1.0
                ex = px - (ax + t*dx); ey = py - (ay + t*dy)
                d2 = ex*ex + ey*ey
            if d2 > best:
                best = d2; bi = k
        if best > t2:
            keep[bi] = True
            stack.append((i, bi)); stack.append((bi, j))
    return [pts[k] for k in range(n) if keep[k]]

def quantize(pts):
    out = []; last = None
    for (x, y) in pts:
        q = (round(x, NDEC), round(y, NDEC))
        if q != last:
            out.append(q); last = q
    return out

def collect(path, min_area, min_hole):
    d = json.load(open(path, encoding="utf-8"))
    rings = []
    for ft in d["features"]:
        g = ft["geometry"]; c = g["coordinates"]
        polys = [c] if g["type"] == "Polygon" else c
        for poly in polys:
            if not poly:
                continue
            ext = quantize(simplify([tuple(p[:2]) for p in poly[0]], TOL))
            if len(ext) < 4 or shoelace(ext) < min_area:
                continue
            sel = [ext]
            for hole in poly[1:]:
                h = quantize(simplify([tuple(p[:2]) for p in hole], TOL))
                if len(h) >= 4 and shoelace(h) >= min_hole:
                    sel.append(h)
            rings.extend(sel)
    return rings

def main():
    print("Natural Earth 10m bathymetry -> bathy_data.js")
    all_bands = []
    for name, depth, ma, mh in BANDS:
        p = fetch(name)
        r = collect(p, ma, mh)
        pts = sum(len(x) for x in r)
        print("  %5dm : %4d rings, %6d points" % (depth, len(r), pts))
        all_bands.append((depth, r))

    buf = bytearray()
    buf += struct.pack("<I", len(all_bands))
    for depth, r in all_bands:
        buf += struct.pack("<II", depth, len(r))
    for depth, r in all_bands:
        for ring in r:
            buf += struct.pack("<I", len(ring))
    total = 0
    for depth, r in all_bands:
        for ring in r:
            for (x, y) in ring:
                xi = max(-32768, min(32767, int(round(x*100))))
                yi = max(-32768, min(32767, int(round(y*100))))
                buf += struct.pack("<hh", xi, yi)
                total += 1
    payload = base64.b64encode(bytes(buf)).decode()
    js = ("// AUTO-GENERATED by build_depth.py - DO NOT EDIT BY HAND\n"
          "// Source: Natural Earth 1:10m bathymetry (public domain)\n"
          "// naturalearthdata.com via nvkelso/natural-earth-vector\n"
          "// Bands are CUMULATIVE: each = area DEEPER than its depth value.\n"
          "// Format: int16 lon*100, lat*100 (0.01deg ~ 1.11km), simplified at 0.03deg.\n"
          "window.BATHY = { scale: 100, tolDeg: %s, points: %d, data: \"%s\" };\n"
          % (TOL, total, payload))
    open(OUT, "w", encoding="utf-8").write(js)
    print("total %d points -> %s (%d KB)" % (total, OUT, os.path.getsize(OUT)//1024))

if __name__ == "__main__":
    main()
