# build_wind.py - NCEP/NCAR 재분석 10m 바람 월별평년값 -> 4도 격자 -> wind_data.js
# 실행: python build_wind.py
# 출처: NOAA PSL, NCEP/NCAR Reanalysis 1 Monthly Long-Term Mean (1991-2020)
#       10m 고도 u/v 성분, T62 가우시안 격자 192x94
#       OPeNDAP ASCII 창구로 받으므로 외부 라이브러리가 필요 없다.
import base64, os, urllib.request

BASE = ("https://psl.noaa.gov/thredds/dodsC/Datasets/"
        "ncep.reanalysis.derived/surface_gauss/")
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "wind_data.js")

NX, NY = 90, 45           # 4도 격자 (칸 하나 = 적도에서 약 445km)
NM = 12                   # 월별 12장
QSTEP = 0.2               # 양자화 단위: 0.2 m/s -> int8 (+-25.4 m/s)
MISS = 1e3                # 결측 판정 (재분석 결측값은 -9.97e36)


def dap(fn, expr, cache):
    """OPeNDAP ASCII 요청. 받은 원문을 캐시에 저장해 재실행 시 재사용."""
    path = os.path.join(HERE, cache)
    if os.path.exists(path) and os.path.getsize(path) > 10000:
        print("  cache hit:", cache)
        return open(path, encoding="ascii", errors="replace").read()
    url = BASE + fn + ".ascii?" + expr
    print("  downloading:", cache, "...")
    req = urllib.request.Request(url, headers={"User-Agent": "build_wind.py"})
    with urllib.request.urlopen(req, timeout=180) as r:
        txt = r.read().decode("ascii", "replace")
    open(path, "w", encoding="ascii", errors="replace").write(txt)
    print("  saved:", cache, len(txt), "bytes")
    return txt


def axis(txt, tag):
    """.ascii 출력에서 좌표축 배열 한 줄을 뽑는다."""
    lines = txt.splitlines()
    for i, ln in enumerate(lines):
        if ln.startswith(tag + "["):
            return [float(x) for x in lines[i + 1].split(",")]
    raise RuntimeError("축을 찾지 못함: " + tag)


def grid3d(txt, var, nm, nlat, nlon):
    """[t][j], v, v, ... 형식의 본문을 [t][j][i] 리스트로 파싱."""
    g = [[None] * nlat for _ in range(nm)]
    key = var + "." + var + "["
    started = False
    for ln in txt.splitlines():
        if ln.startswith(key):
            started = True
            continue
        if not started:
            continue
        if not ln.startswith("["):
            if g[0][0] is not None:      # 본문이 끝나고 MAPS 구역 시작
                break
            continue
        head, _, rest = ln.partition(",")
        t, j = head.strip().strip("[]").split("][")
        row = [float(x) for x in rest.split(",")]
        if len(row) != nlon:
            raise RuntimeError(f"열 개수 불일치 {len(row)} != {nlon}")
        g[int(t)][int(j)] = row
    for m in range(nm):
        for j in range(nlat):
            if g[m][j] is None:
                raise RuntimeError(f"빠진 행 t={m} j={j}")
    return g


def downsample(g, lat, lon, nm):
    """가우시안 192x94 -> 등간격 4도 90x45 (면적 가중 없이 단순 평균)."""
    out = []
    for m in range(nm):
        s = [0.0] * (NX * NY)
        c = [0] * (NX * NY)
        for j, la in enumerate(lat):
            tj = int((90.0 - la) // 4)
            tj = 0 if tj < 0 else (NY - 1 if tj >= NY else tj)
            row = g[m][j]
            base = tj * NX
            for i, lo in enumerate(lon):
                v = row[i]
                if abs(v) > MISS:
                    continue
                lw = ((lo + 180.0) % 360.0) - 180.0
                ti = int((lw + 180.0) // 4)
                ti = 0 if ti < 0 else (NX - 1 if ti >= NX else ti)
                k = base + ti
                s[k] += v
                c[k] += 1
        out.append([(s[i] / c[i]) if c[i] else 0.0 for i in range(NX * NY)])
    return out


def quant(vals):
    b = bytearray()
    for x in vals:
        q = int(round(x / QSTEP))
        q = -127 if q < -127 else (127 if q > 127 else q)
        b.append(q & 0xFF)
    return b


def main():
    print("[1/4] 다운로드")
    full = "[0:1:11][0:1:93][0:1:191]"
    tu = dap("uwnd.10m.mon.ltm.nc", "uwnd" + full, "wind_u_raw.txt")
    tv = dap("vwnd.10m.mon.ltm.nc", "vwnd" + full, "wind_v_raw.txt")
    lat = axis(tu, "uwnd.lat")
    lon = axis(tu, "uwnd.lon")
    print(f"      원본 격자 {len(lon)}x{len(lat)}  lat {lat[0]:.2f}~{lat[-1]:.2f}")

    print("[2/4] 파싱")
    gu = grid3d(tu, "uwnd", NM, len(lat), len(lon))
    gv = grid3d(tv, "vwnd", NM, len(lat), len(lon))

    print(f"[3/4] {NX}x{NY} (4도) 로 축소")
    du = downsample(gu, lat, lon, NM)
    dv = downsample(gv, lat, lon, NM)

    speeds = []
    for m in range(NM):
        for i in range(NX * NY):
            speeds.append((du[m][i] ** 2 + dv[m][i] ** 2) ** 0.5)
    speeds.sort()
    p50 = speeds[len(speeds) // 2]
    p99 = speeds[int(len(speeds) * 0.99)]
    mx = speeds[-1]
    print(f"      풍속 중앙 {p50:.2f} / p99 {p99:.2f} / 최대 {mx:.2f} m/s")

    print("[4/4] wind_data.js 기록")
    buf = bytearray()
    for m in range(NM):
        buf += quant(du[m])
    for m in range(NM):
        buf += quant(dv[m])
    payload = base64.b64encode(bytes(buf)).decode()
    js = (
        "// AUTO-GENERATED by build_wind.py - DO NOT EDIT BY HAND\n"
        "// Source: NOAA PSL, NCEP/NCAR Reanalysis 1 Monthly Long-Term Mean\n"
        "//         10m u/v wind, T62 Gaussian 192x94 -> 4deg 90x45, 12 months\n"
        "// Public domain (U.S. Government work). See SOURCES_LICENSE.md\n"
        "window.WIND = {\n"
        f"  nx: {NX}, ny: {NY}, months: {NM},\n"
        f"  quantStep: {QSTEP},          // int8 * quantStep = m/s\n"
        f"  p99: {p99:.4f},              // 밝기/굵기 정규화 기준\n"
        "  // layout: u[month0..11] then v[month0..11], each ny*nx, row-major from 90N\n"
        f'  data: "{payload}"\n'
        "};\n"
    )
    open(OUT, "w", encoding="utf-8").write(js)
    print(f"      완료: wind_data.js  {os.path.getsize(OUT)/1024:.0f} KB "
          f"(원시 {len(buf)} bytes)")


if __name__ == "__main__":
    main()
